version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0   # Update to 7.0 or 8.0 if your Lambda uses newer runtime
    commands:
      - echo "Installing Amazon Lambda Tools..."
      - dotnet tool install -g Amazon.Lambda.Tools
      - export PATH="$PATH:/root/.dotnet/tools"

  pre_build:
    commands:
      - echo "Restoring dependencies..."
      - dotnet restore C:\Users\C5396794\source\repos\SamplehellowworldLambda\src\Helloworld.csproj
  build:
    commands:
      - echo "hello world"
      - dotnet build C:\Users\C5396794\source\repos\SamplehellowworldLambda\src\Helloworld.csproj --configuration Release
      - echo "Packaging Lambda..."
      - dotnet lambda package \
          --project-location C:\Users\C5396794\source\repos\src\SamplehellowworldLambda\
          --configuration Release \
          --output-package bin\release\LambdaFn.zip
post_build:
    commands:
      - echo "Deploying Lambda..."
      - dotnet lambda deploy-function SamplehellowworldLambda\
          --function-name helloworldsamplelatest \
          --region us-west-2 \   # Change to your AWS region
          
artifacts:
  files:
    - C:\Users\C5396794\source\repos\SamplehellowworldLambda\SamplehellowworldLambda\bin\release\LambdaFn.zip
  discard-paths: yes